__default__:
  mem: "100GB"
  time: "24:00:00"
  nodes: 1
  ntasks: 1
  log: "logs/slurm.%j.log"

,download_reads_paired:
  mem: "10GB"
  time: "10:00:00"
  nodes: 1
  ntasks: 1
  log: "logs/slurm.%j.log"
download_reads_single:
  mem: "10GB"
  time: "10:00:00"
  nodes: 1
  ntasks: 1
  log: "logs/slurm.%j.log"
fastqc:
  mem: "10GB"
  time: "10:00:00"
  nodes: 1
  ntasks: 1
  log: "logs/slurm.%j.log"
download_reads_single:
  mem: "10GB"
  time: "10:00:00"
  nodes: 1
  ntasks: 1
  log: "logs/slurm.%j.log"
dada_filter_and_trim_paired:
  mem: "10GB"
  time: "10:00:00"
  nodes: 1
  ntasks: 1
  log: "logs/slurm.%j.log"
dada_filter_and_trim_single: 
  mem: "10GB"
  time: "10:00:00"
  nodes: 1
  ntasks: 1
  log: "logs/slurm.%j.log"